# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_graph.ipynb.

# %% auto 0
__all__ = ['Graph']

# %% ../nbs/01_graph.ipynb 4
class Graph:
    "2d representation of some function"
    def __init__(self,
                 x:float, # independent variable
                 y:float, # independent variable
                 name:str # graph name
                ): 
        self.x, self.y, self.name = x, y, name
    def get_x(self):
        return self.x
    def get_y(self):
        return self.y
    def get_name(self):
        return self.name
        
        
