# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_main.ipynb.

# %% auto 0
__all__ = ['X', 'Y1', 'Y2', 'Y3']

# %% ../nbs/03_main.ipynb 4
import matplotlib.pyplot as plt
import numpy as np
import math
from .graph import Graph as Graph
from .plot import SimplePlot as MyPlot

# %% ../nbs/03_main.ipynb 5
X = np.arange(0, math.pi * 2, 0.001)
Y1 = np.sin(X)
Y2 = np.cos(X)
Y3 = np.tan(X)
