# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_plot.ipynb.

# %% auto 0
__all__ = ['SimplePlot']

# %% ../nbs/02_plot.ipynb 4
class SimplePlot:
    def __init__(self):
        self.graph_list = []
    def set_plot(self, plot):
        self.plt = plot
    def add_graph(self, graph):
        self.graph_list.append(graph)
    def plot_first_graph(self):
        if len(self.graph_list) != 0:
            self.plt.suptitle(self.graph_list[0].get_name())
            self.plt.plot(self.graph_list[0].get_x(),self.graph_list[0].get_y())
